name: webai-hackathon-2025

services:
  database:
    image: postgres:17.5
    restart: unless-stopped
    shm_size: 1g
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=webai_hackathon
    env_file:
      - ./.env
